Update README.md
artemkin/git-lfs-server pull request #9
Opened 2018-02-01 18:04 UTC by joshlk

Added example as discussed in #7

2018-02-03 10:16 UTC, artemkin requested changes
Added a couple of issues to be addressed before merging.

Thank you for your work!

2018-02-03 10:16 UTC, artemkin commented on README.md
> +mkfile -n 10m test.bin
mkfile is not available on linux

dd is more universal way to create a file

dd if=/dev/zero of=test.bin count=10240 bs=1024

2018-02-03 10:16 UTC, artemkin commented on README.md
> +git lfs install
git lfs command is not available by default, you have to install git lfs client first. Maybe need to add a note about it.

2018-02-03 10:16 UTC, artemkin commented on README.md
> +git config -f .lfsconfig lfs.url http://localhost:5000
lfs server listens 8080 port by default.

2018-02-03 10:16 UTC, artemkin commented on README.md
> +git add .lfsconfig
Don't forget to commit .lfsconfig. When you clone the repo, git lfs will find this config and download lfs files automatically.

2018-02-08 11:16 UTC, joshlk reviewed
Cheers 👍 . Changes are in

2018-02-08 18:21 UTC, artemkin approved these changes

2018-02-08 18:22 UTC, merged

2018-02-08 18:22 UTC, artemkin commented
@joshlk Perfect! Thank you